// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ_OTGChRVQV4lSdzr-CGQ5oUT_MGLzgU',
    appId: '1:117070778533:web:f858f8b27c0f5ebf057d4c',
    messagingSenderId: '117070778533',
    projectId: 'flutter-mvvm-demo',
    authDomain: 'flutter-mvvm-demo.firebaseapp.com',
    storageBucket: 'flutter-mvvm-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2sPB5Z1YHrDqrWOHOXGFKCz2GFr7KNrY',
    appId: '1:117070778533:android:254e2549c5c106ac057d4c',
    messagingSenderId: '117070778533',
    projectId: 'flutter-mvvm-demo',
    storageBucket: 'flutter-mvvm-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKd2pNpvCY6k4CxBLbw-6wJFUU7EU2ha0',
    appId: '1:117070778533:ios:11353720bbf6d0e2057d4c',
    messagingSenderId: '117070778533',
    projectId: 'flutter-mvvm-demo',
    storageBucket: 'flutter-mvvm-demo.appspot.com',
    iosBundleId: 'com.example.flutterApplicationViaje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKd2pNpvCY6k4CxBLbw-6wJFUU7EU2ha0',
    appId: '1:117070778533:ios:c7d7147ec2df721e057d4c',
    messagingSenderId: '117070778533',
    projectId: 'flutter-mvvm-demo',
    storageBucket: 'flutter-mvvm-demo.appspot.com',
    iosBundleId: 'com.example.flutterApplicationViaje.RunnerTests',
  );
}
